[package]
name = "Cycle"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.17.3"

[dev-dependencies]
rand = "0.8"
criterion = { version = "0.7", features = ["html_reports"] }

[profile.dev.package."*"]
opt-level = 3
